/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GalleryCategory = IDL.Variant({
  'activities' : IDL.Null,
  'events' : IDL.Null,
  'campus' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const AdmissionEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'preferredClass' : IDL.Text,
  'studentName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'parentName' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'category' : GalleryCategory,
  'uploadDate' : Time,
});
export const NewsAnnouncement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publicationDate' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, GalleryCategory, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'createNews' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteImage' : IDL.Func([IDL.Nat], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactFormSubmission)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(AdmissionEnquiry)], ['query']),
  'getAllImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsAnnouncement)], ['query']),
  'getImage' : IDL.Func([IDL.Nat], [GalleryImage], ['query']),
  'getImagesByCategory' : IDL.Func(
      [GalleryCategory],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'submitAdmissionEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GalleryCategory = IDL.Variant({
    'activities' : IDL.Null,
    'events' : IDL.Null,
    'campus' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const AdmissionEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'preferredClass' : IDL.Text,
    'studentName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'category' : GalleryCategory,
    'uploadDate' : Time,
  });
  const NewsAnnouncement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publicationDate' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, GalleryCategory, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'createNews' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteImage' : IDL.Func([IDL.Nat], [], []),
    'getAllContacts' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(AdmissionEnquiry)], ['query']),
    'getAllImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsAnnouncement)], ['query']),
    'getImage' : IDL.Func([IDL.Nat], [GalleryImage], ['query']),
    'getImagesByCategory' : IDL.Func(
        [GalleryCategory],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'submitAdmissionEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };