/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionEnquiry {
  'id' : bigint,
  'preferredClass' : string,
  'studentName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'parentName' : string,
}
export interface ContactFormSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export type GalleryCategory = { 'activities' : null } |
  { 'events' : null } |
  { 'campus' : null };
export interface GalleryImage {
  'id' : bigint,
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
  'category' : GalleryCategory,
  'uploadDate' : Time,
}
export interface NewsAnnouncement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publicationDate' : Time,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGalleryImage' : ActorMethod<
    [string, string, GalleryCategory, ExternalBlob],
    bigint
  >,
  'createNews' : ActorMethod<[string, string], bigint>,
  'deleteImage' : ActorMethod<[bigint], undefined>,
  'getAllContacts' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllEnquiries' : ActorMethod<[], Array<AdmissionEnquiry>>,
  'getAllImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllNews' : ActorMethod<[], Array<NewsAnnouncement>>,
  'getImage' : ActorMethod<[bigint], GalleryImage>,
  'getImagesByCategory' : ActorMethod<[GalleryCategory], Array<GalleryImage>>,
  'submitAdmissionEnquiry' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];